### ISSUE TITLE
Unable to read my project's GCR image paths

### ISSUE THREAD

**Issue by cybrcodr** [GoogleCloudPlatform/container-diff#114]
Related to issue #48 but for remote paths.
```
$ container-diff analyze us.gcr.io/<project>/appengine/default.20171006t183930:latest
E1010 10:01:15.568136   40141 image_prep_utils.go:99] denied: Permission denied for "latest" from request "/v2/<project>/appengine/default.20171006t183930/manifests/latest".
E1010 10:01:15.569398   40141 analyze.go:46] Error processing image: denied: Permission denied for "latest" from request "/v2/<project>/appengine/default.20171006t183930/manifests/latest".
```

I'm guessing this has to do with permissions on my project's GCR paths.  There's doc on how to make the GCR path public -- https://cloud.google.com/container-registry/docs/access-control.  Not easy to figure out the corresponding GS bucket path for it though.

Anyways, filing this feature request if somehow container-diff can be made to use my project's token authentication to analyze a remote image w/o changing ACLs.

**Comment by dlorenc** [comment]
@cybrcodr this should be possible if you configure the gcr credential helper, following these instructions: https://github.com/GoogleCloudPlatform/docker-credential-gcr

Could you give that a try? I'll keep this open to add documentation on how to use that.

**Comment by cybrcodr** [comment]
I downloaded docker-credential-gcr, built it and then run "docker-credential-gcr configure-docker".

Running container-diff on those images works now!  Thanks!
