### ISSUE TITLE
no filesystem diff found for different images

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/container-diff#139]
Readme says:

> container-diff is a tool for analyzing and comparing container images. container-diff can examine images along several different criteria, including:
>
> -    Docker Image History
> -    Image file system
> - ...

But when I run:

     ./container-diff-darwin-amd64 diff daemon://golang:1.9-alpine daemon://golang:1.8-alpine

I actually don't get an "image filesystem diff"

```

-----Apt-----

Packages found only in golang:1.9-alpine: None

Packages found only in golang:1.8-alpine: None

Version differences: None
```

I actually expected to see something like `git status` diff output saying these are the files that are in image A, and not in B (or vice versa) and here are the files that are different between two images.

This tool does not seem to be doing this. So maybe the statement about "Image file system" diffing should be removed.

**Comment by dlorenc** [comment]
The default diff type is just "apt", maybe we should change that or clarify the docs. If you pass
`--type=file` it should give you the type of output you're looking for.

**Comment by ahmetb** [comment]
My bad, I should've read the documentation better.

**Comment by dlorenc** [comment]
Thanks for trying the tool! We disabled the file differ by default because it can be very verbose on larger images with lots of changes, but maybe we should make it more clear.
