### ISSUE TITLE
Add flag to force local images

### ISSUE THREAD

**Issue by clarson99** [GoogleCloudPlatform/container-diff#143]
This would be so much more useful if i could work with local images instead of having it try to fetch from a repo i may or may not have access to.  Please consider adding a flag such as --local-images-only.

**Comment by dlorenc** [comment]
Hey,

You should be able to use local images already either by specifying the path to a "docker save" formatted tar or by specifying the name of the image with the "daemon://" prefix.

Do either of these work for you?

**Comment by dlorenc** [comment]
Note that we considered making this behavior a flag, but the semantics seemed a little weird when diffing two images, where a common case is one local vs. one remote.

**Comment by nkubala** [comment]
@clarson99 closing this for now, let us know if you still have issues with this.

**Comment by yarikoptic** [comment]
I was lucky to find this issue since I was about to beg the same ;-)  Now adding `daemon://` and it seems to work!  hopefully I will not forget about it (--help output didn't mention it) and find reading my own post in a month or two ;)
