### ISSUE TITLE
RFC: add RPM support

### ISSUE THREAD

**Issue by vrothberg** [GoogleCloudPlatform/container-diff#146]
I am currently having a look at extending containerdiff to support rpm packages to further support SUSE and RedHat based images.  But before going down the rabbit hole, I want to have some feedback from the maintainers.

The main issue with RPM is that it doesn't expose its package base as a text file (as apt does) but as Berkeley databases, which complicates things quite a bit. So far, I can think of two potential solutions:

1. Run the image in a container and do something like `rpm -qa --qf "%{NAME}\t%{VERSION}\t%{SIZE}\n"`. That's pretty straightforward and avoids to add more dependencies (docker is already vendored), but it requires running a container.
2. Parse the databases in `/var/lib/rpm/*`. I had a look at some older golang Berkeley bindings that use the C API, but none of them are well maintained, if at all. So I suggest to use the rpm C API directly and write a go library to add those bindings. However, I am not sure how or if the C API runs on Windows. This would require some more research and testing.

I have a strong preference for option (1) as it's more portable while adding no additional dependencies. It only requires dockerd to be running. Option (2) brings up more issues, as the rpm go library must be maintained as well. I'm willing to implement it, but the main focus would be to just get the things in place to extract the relevant data from the databases.

What are your thoughts on that? I can imagine that rpm support has already been considered.

**Comment by dlorenc** [comment]
Thanks for looking into this. Option #1 sounds fine for now, we just need to make sure we handle the case of a user not having a running docker daemon well. I currently have some experience with the fsouza go-dockerclient library and prefer it to the standard Docker one.

Is this something you're interested in contributing?

**Comment by vrothberg** [comment]
> Is this something you're interested in contributing?

@dlorenc, yes I am interested. Most of the code for option (1) is already in place, and I can extend it to run in a container next week.  `github.com/fsouza/go-dockerclient` looks good to me, so if you prefer this API I can use it instead of docker/docker.

Regarding the use case of not having a daemon running, I suggest to exit(1) with a warning when running with `-t rpm`. Do you have some specific requests for the error handling?

**Comment by dlorenc** [comment]
@vrothberg Great to hear. Let us know when you have something ready for review!

That sounds fine for error handling. I just want to make sure users get a clear, actionable error when there is no docker daemon present, and that users don't think they need a docker daemon for *all* differs.

**Comment by vrothberg** [comment]
@dlorenc Thanks! It's working nicely with running rpm queries in containers for openSUSE and Fedora images. There's only one problem related to tar archives.  In case of a tar archive, it should be imported to the daemon, executed and subsequently removed. However, no matter which archive I use, I'm experiencing errors such as `WARN[0000] Diff may be inaccurate: unsupported file type 50 found in file bin/dnsdomainname tar  [...]` leading to an empty `pkgutil.Image`. Maybe I misinterpreted the README, but I assumed that a `docker export` tar archive was a valid input, is it?

**Comment by vrothberg** [comment]
I just figured that tar archives generated by `docker save` work and will stick with those for now.

**Comment by dlorenc** [comment]
Ah, yeah that's unfortunately confusing. `docker save` and `docker export` tarballs are completely different. We should eventually support both formats, but in the meantime a more useful error message would be nice.
