### ISSUE TITLE
[RFC] run rpm queries locally on Linux hosts with rpm installed

### ISSUE THREAD

**Issue by vrothberg** [GoogleCloudPlatform/container-diff#178]
The RPMAnalyzer performs the analysis (i.e., rpm queries) inside a Docker container to make it portable across all target platform of container-diff. The portability comes at the cost of (considerable) performance overheads on Linux hosts that have rpm installed, where the rpm queries can be executed locally on the unpacked rootfs of the analyzed image.

One way to overcome the above issue is to check at run-time if the rpm binary is installed on the host and execute the rpm queries locally instead of running them inside a container. However, before opening a PR, I'd like to ask the maintainers for feedback. What do you think? On the long run, rpm-bindings for golang would be ideal but there is no library (yet).

Cc: @nkubala

**Comment by vrothberg** [comment]
Running the analysis doesn't seem to be generically applicable. First, the local of the rpm database varies depending on the distribution and version. Second, querying the path of the database (i.e., `rpm -E '%_dbpath) requires to chroot into the unpacked rootfs of the image, which is likely to fail as there is no guarantee that image ships the required locales. All other solutions and workarounds (e.g., searching the rpm macros file "manually") are rather hacky and require to expand the macros without the help of rpm.

**Comment by nkubala** [comment]
@vrothberg thanks for filing, and sorry for the really late reply on this one. This would be really nice to fix but seems like it might be more trouble than it's worth right now. The performance overhead is certainly annoying but I don't think it's a dealbreaker at this time, and based on your analysis I can't really see a "catch-all" solution to this that doesn't have the potential to introduce more complexity. For now I think we'll put this on the backburner, but feel free to reopen if something more elegant comes to mind :)
