### ISSUE TITLE
error "invalid reference format" when using a remote:// registry since version 0.7.0

### ISSUE THREAD

**Issue by hoexter** [GoogleCloudPlatform/container-diff#204]
Hi,
starting with release 0.7.0 container-diff no longer works when addressing a remote:// registry.
Diffing two local - as in daemon:// - images still works fine.

$ sudo /home/sven/container-diff-linux-amd64 diff --type=file -j -n daemon://docker-registry.mycorp.com/mycorp-debian:9.201803191406 remoe://docker-registry.mycorp.com/mycorp-debian:9.latest 2>&1|head
Starting diff on images daemon://docker-registry.mycorp.com/mycorp-debian:9.201803191406 and remote://docker-registry.mycorp.com/mycorp-debian:9.latest, using differs: [file]
Retrieving image docker-registry.mycorp.com/mycorp-debian:9.201803191406 from source Local Daemon
time="2018-03-19T17:26:36+01:00" level=error msg="invalid reference format"

I'm not sure if this is an issue with container-diff itself or with a 3rd party lib. Downgrading back to 0.6.2 works. I also build the current master but that one shows the same issue.

**Comment by vrothberg** [comment]
I can confirm the issue for both, HEAD and 0.7.0. It seems that the `remote://` prefix is not removed when parsing the image reference (https://github.com/GoogleCloudPlatform/container-diff/blob/master/cmd/root.go#L148).

**Comment by nkubala** [comment]
Yep, looks like we broke parsing at some point recently. Working on a fix, I'll get a release out as soon as it's in. The real question is, how did our integration tests not catch this :fearful:

**Comment by vrothberg** [comment]
@nkubala I have a fix in place :-D About to open PR.

**Comment by vrothberg** [comment]
@nkubala https://github.com/GoogleCloudPlatform/container-diff/pull/206. Feel free to edit, close, etc. (my working day's about to end).

**Comment by hoexter** [comment]
Wow that was fast! Thanks a lot @vrothberg and @nkubala, I can confirm it works again.
