### ISSUE TITLE
"failed to untar layer with error ... too many open files"

### ISSUE THREAD

**Issue by duggelz** [GoogleCloudPlatform/container-diff#33]
Running the linux binary downloaded 2017-08-18 on a Goobuntu workstation shows no packages and incorrect diff.

$ md5sum /usr/local/bin/container-diff-amd64-linux
6b08c116217e7a7aee6c7a7306bf2d54  /usr/local/bin/container-diff-amd64-linux

$ sudo /usr/local/bin/container-diff-amd64-linux gcr.io/google-appengine/python:2017-07-25-110644 gcr.io/google-appengine/python:2017-08-18-131018  >stdout.txt 2>stderr.txt

[stderr.txt](https://github.com/GoogleCloudPlatform/container-diff/files/1235942/stderr.txt)
[stdout.txt](https://github.com/GoogleCloudPlatform/container-diff/files/1235943/stdout.txt)

**Comment by r2d4** [comment]
Able to reproduce from the release binary, but not at HEAD.  I think this has been resolved @nkubala?

**Comment by nkubala** [comment]
cool, we'll just need to do a release to push this change out
