### ISSUE TITLE
Provide makefile to build tool

### ISSUE THREAD

**Issue by cftorres** [GoogleCloudPlatform/container-diff#4]
Originally submitted by @r2d4: "I would like to run $ make to build the idiff tool to a .gitignored directory. I think it could be simple for now, with just one target to build the idiff binary, and another one to install to $GOBIN. In the future, it might be cool to also support dockerized builds."

**Comment by duggelz** [comment]
As a first step, instructions on how to build the tool in the README.md would be good.  Not being a Go developer, it seems like I have to name the containing directories in some particular way and set GOPATH to something?

**Comment by duggelz** [comment]
After getting it working, I have no good idea how to turn it into a Makefile, given that several steps need to happen before even cloning the repo.  Maybe with symlinks.  For posterity, here's what worked for me on a Ubuntu-like workstation:

```shell
# [Go compiler and runtime already installed]
rm -rf ~/code/workspace1
export GOPATH=~/code/workspace1
go get github.com/tools/godep
export PATH=$PATH:~/code/workspace1/bin
cd code/workspace1/
mkdir -p src/github.com/GoogleCloudPlatform
cd src/github.com/GoogleCloudPlatform
git clone git@github.com:GoogleCloudPlatform/container-diff.git
cd container-diff/
godep restore
go get code.cloudfoundry.org/bytefmt  # Presumably can be fixed with godeps somehow
godep go build main.go
./main [arguments]
```

**Comment by r2d4** [comment]
I'll take a stab at this
