### ISSUE TITLE
Got permission denied with a normal user

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/container-diff#45]
$ container-diff gcr.io/google-appengine/php71:2017-08-22-15-24 gcr.io/google-appengine/php71
E0825 16:15:04.495977   16521 image_prep_utils.go:121] open /etc/docker/certs.d/gcr.io: permission denied
E0825 16:15:04.496338   16521 root.go:84] open /etc/docker/certs.d/gcr.io: permission denied

**Comment by r2d4** [comment]
Fixed by #39.  This can be closed.
