### ISSUE TITLE
Feature request: allow to retrieve RPM package list

### ISSUE THREAD

**Issue by gbraad** [GoogleCloudPlatform/container-diff#53]
Would be great to be able to get more information related to RPM packages (Fedora, CentOS, RHEL, etc).

Will have a look at this and might come up with a PR.

**Comment by vrothberg** [comment]
I had a look at this today and wrote a proposal in #146.

**Comment by vrothberg** [comment]
@nkubala @gbraad #146 has been merged, so this issue can be closed.

**Comment by gbraad** [comment]
sorry, completely missed this... Great!
