### ISSUE TITLE
Change differ CLI to support a list of differs instead of independent flags

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleCloudPlatform/container-diff#64]
Currently container-diff has multiple flag toggles for each differ.  The CLI should instead support a better method for passing in a list of differs.

**Comment by aaron-prindle** [comment]
The CLI for this would be something like:
container-diff diff --differs=apt,pip <image1> <image2>
container-diff analyze --differs=apt,node <image1>
I'm going to move forward with this for now, let me know if there any other input on this.

**Comment by aaron-prindle** [comment]
In the documentation and code, the terms differ and analyzer are used somewhat interchangeably, does anyone have an opinion on the flag name or what they should be called.  Going with analyzers for now

**Comment by dlorenc** [comment]
SGTM.

**Comment by r2d4** [comment]
I'll throw `--type` out there, since diff or analyze is already stated in the subcommand

**Comment by dlorenc** [comment]
I think this is fixed right? #68
