### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by r2d4** [GoogleCloudPlatform/container-diff#79]

**Comment by r2d4** [comment]
Two things left to do:

- [] Bump the version in the makefile
- [] Add a makefile rule that depends on `cross` and uploads to GCS

**Comment by zombiezen** [comment]
Seems like the binaries are not available in the GCS bucket.

**Comment by r2d4** [comment]
The github release paths are incorrect

They are container-diff-amd64-linux, when they should really be `container-diff-linux-amd64`

cc @aaron-prindle @nkubala

**Comment by aaron-prindle** [comment]
updated, we recently renamed the binaries but did not update the release page.  This should be fixed now, thanks for catching this

**Comment by r2d4** [comment]
```
https://storage.googleapis.com/container-diff/v0.4.1/container-diff-darwin-amd64
https://storage.googleapis.com/container-diff/v0.4.1/container-diff-linux-amd64
https://storage.googleapis.com/container-diff/v0.4.1/container-diff-windows-amd64.exe
```
