### ISSUE TITLE
ImagePrepper should use ImageReference

### ISSUE THREAD

**Issue by r2d4** [GoogleCloudPlatform/container-diff#99]
> I think the real problem here is that ImagePrepper shouldn't have Source be a string but it should actually be a containers/image types.ImageReference, which is exactly what you can pass into all of the containers/images functions without have to worry about parsing it at the end.

https://github.com/GoogleCloudPlatform/container-diff/pull/97#discussion_r140114511

**Comment by nkubala** [comment]
The code has since been refactored to remove the `ImagePrepper` in favor of a `Prepper` interface that preppers implement. Since not all of them use the containers/image methods (e.g. the Tar prepper), we can't have the `Prepper` contain the `ImageReference` directly. Going to close this for now.
